svg_icons:
  default: "moon|sun"
  type: "list"
  list_type: "compact"
remove_color_scheme_toggle_from_header:
  default: false
  type: bool
  description: "Do not show color scheme toggle button in site header"
